[default]
defaultServerAddress="tcp"
defaultServerAddress = "10.252.1.0/24"
defaultServerPort = 51820
defaultDNS = "1.1.1.1"
defaultMTU = 1450
defaultPersistentKeepalive = 15
defaultConfigFilePath = "/etc/wireguard/wg0.conf"